name: Deploy

on:
    push:
        branches: ['main']

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - uses: pnpm/action-setup@v6
              name: Install pnpm
              with:
                  version: 10
                  cache: true

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm build

            - name: Configure pages
              uses: actions/configure-pages@v5

            - name: Upload pages artifact
              uses: actions/upload-pages-artifact@v5
              with:
                  path: './dist'

            - name: Deploy pages
              id: deployment
              uses: actions/deploy-pages@v5
